### ISSUE TITLE
Responsive issue in User side. (14 inch screen)

### ISSUE THREAD

**Issue by devaprasadnm** [sharunrajeev/studentManagementSystem#29]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/56536197/173905994-c8378e5e-8ee3-474d-ad62-231759ae4e01.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/56536197/173906148-4d035d0e-6c13-4aeb-a648-51e9dbe92d76.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/56536197/173906232-8e4a0d97-c01d-4e80-95f2-1ae089b258e0.png">
 But payment section is ok

**Comment by Revnth** [comment]
I'll check it
